version: 0.2

phases:
  pre_build:
    commands:
    - echo upload source to s3 for pipeline...
    - aws --version
    - echo "AWS_REGION is $AWS_REGION "
    - echo "Source bucket is $SOURCE_BUCKET"
  build:
    commands: -echo "list directory" - ls
    #- aws cp --recursive ./ $SOURCE_BUCKET
  post_build:
    commands:
    - echo Get Source completed on `date`
