module "ecs-autoscaling" {
  source                     = "./modules/ecs-autoscaling"
  Env-Name                   = "${var.Env-Name}"
  cluster_name               = "${var.Env-Name}-backend-cluster"
  key_name                   = "${var.ssh-key-name}"
  instance_type              = "t2.medium"
  region                     = "${var.aws-region}"
  availability_zones         = "${join(",", values(var.zone-names))}"
  subnet_ids                 = "${join(",", aws_subnet.wifi-backend-subnet.*.id)}"
  security_group_ids         = "${join(",", var.backend-sg-list)}"
  backend-cpualarm-count     = "${var.backend-cpualarm-count}"
  min_size                   = "${var.backend-min-size}"
  max_size                   = "10"
  desired_capacity           = "${var.backend-instance-count}"
  instance-profile-id        = "${aws_iam_instance_profile.ecs-instance-profile.id}"
  ami                        = "${var.ami}"
  critical-notifications-arn = "${var.critical-notifications-arn}"
  capacity-notifications-arn = "${var.capacity-notifications-arn}"
  users                      = "${var.users}"
}
